<?php

/* @var $this yii\web\View */

use dmitrybtn\yimp\Yimp;
use yii\bootstrap4\Html;

?>
<div class="site-index">

    <div class="jumbotron">
        <h1>Hey there!</h1>

        <p class="lead">This is live demo for YIMP - dashboard for <a href="http://yiiframework.com" target="_blank">Yii Framework</a> based on
            <a href="https://getbootstrap.com" target="_blank">Bootstrap 4</a>.

        </p>
        <p class="lead">
            Useful links:
            <?php echo Html::a('YIMP on Github', 'https://github.com/dmitrybtn/yii2-yimp') ?>,
            <?php echo Html::a('YIMP on Packagist', 'https://packagist.org/packages/dmitrybtn/yii2-yimp') ?>.
        </p>

        <p>
            Code of this project is also <?php echo Html::a('available on Github', 'https://github.com/dmitrybtn/yii2-yimp-demo') ?>.
            It is based on <?php echo Html::a('Yii 2 basic app template', 'https://github.com/yiisoft/yii2-app-basic') ?>
            with minimal changes. Code of CRUD controller was generated by Gii with YIMP template without any changes except few stubs.
        </p>

    </div>

</div>

<?php $this->beginBlock(Yimp::SIDEBAR_RIGHT); ?>
    <div class="border rounded p-3 mt-3">
        <div class="h5">Widget</div>
        <p class="text-secondary">
            This widget was defined <strong>in action</strong>, so it is visible only for this action.
        </p>

        <p class="text-secondary mb-0">
            Note, that sidebar widgets are visible only on desktops.
        </p>
    </div>
<?php $this->endBlock(); ?>